apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv-data
  namespace: mateapp
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  accessModes:
   - ReadWriteMany
  capacity:
      storage: 1Gi
  hostPath:
    path: /app/data

